### ISSUE TITLE
Generalise function to handle projected data input

### ISSUE THREAD

**Issue by ianjonsen** [jamesgrecian/mapr#1]
Less an issue, more a feature request. I have SSM-filtered tracks that are output from foieGras as sf data.frames with either mercator (epsg=3395) or stereographic polar projections (epsg=3031 or 3995). It would be great to use mapr to generate the coastline data for plotting directly from these data inputs.

**Comment by jamesgrecian** [comment]
Great idea @ianjonsen!

I've edited the function so that it grabs the projection from an `sf` tibble if available.

The issue I've had is that in order to make handling the global shapefile easier I split it into N and S hemisphere's based on the mean latitude of the input data. This was easy to grab from the tibble, less easy to grab from a projected `sf` tibble. I've addressed this by briefly reprojecting back to WGS84 to grab the latitude.

I've also defined a default buffer so that the call to mapr can be simplified to something like:

`data(ellie)`
`# convert ellie to sf tibble with EPSG 3031 projection`
`ellie <- ellie %>%`
` st_as_sf(coords = c("lon", "lat")) %>%`
`sf::st_set_crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>%`
`sf::st_transform(3031)`

`world_shp <- mapr(ellie)`

`p1 <- ggplot() +`
`geom_sf(aes(), data = world_shp) +`
`geom_sf(aes(), data = ellie)`
`print(p1)`

**Comment by ianjonsen** [comment]
works nicely @jamesgrecian! So here's something extra... I just started using `rnaturalearth` & `rnaturalearthdata` pkgs. You can specify one of 3 resolutions BUT perhaps the best part is that you can get coastline or land data as an `sf` tibble. May not be worth your hassle at the moment but this data set looks quite flexible...

`# scale = 50 requires rnaturalearthdata` I think...
`coast <- rnaturalearth::ne_countries(scale=50, returnclass = "sf")`

this _should_ allow you to simplify `mapr` transformations a bit. So here's a full worked example, not w `mapr`, using `rnaturalearth` with the `ellie` data:

`coast <- rnaturalearth::ne_countries(scale=50, returnclass = "sf") %>%`
  `sf::st_transform(crs = 3032) ## Australian Antarctic Polar Stereographic projection`

`ellie_sf <- sf::st_as_sf(ellie, coords = c("lon", "lat"), crs = 4326) %>%`
 ` sf::st_transform(crs = 3032)`

`## define projected data limits and extend by 20%`
`bounds <- sf::st_bbox(ellie_sf)`
`bounds[c("xmin","xmax")] <- extendrange(bounds[c("xmin","xmax")], f = 0.2)`
`bounds[c("ymin","ymax")] <- extendrange(bounds[c("ymin","ymax")], f = 0.2)`

`ggplot() +`
` geom_sf(data = coast, lwd = 0, fill = grey(0.8)) +`
` xlim(bounds[c("xmin","xmax")]) +`
` ylim(bounds[c("ymin","ymax")]) +`
` geom_sf(data = ellie_sf, size = 0.25)`

![Rplot](https://user-images.githubusercontent.com/9984184/55553953-fae7a600-56b7-11e9-9aae-cfbe7a5abeff.jpeg)

**Comment by ianjonsen** [comment]
oops, didn't mean to close the issue - was going to leave that up to you!

**Comment by jamesgrecian** [comment]
The `rworldmap` packages uses the Natural Earth database, so it would be possible to add a resolution (Coarse, Low, High) to `mapr`. I've been importing the low resolution dataset `sf::st_as_sf(rworldmap::countriesLow)` which should match `rnaturalearth::ne_countries(scale=50)`

I didn't know that you could import a `sf` tibble from `rnaturalearth` directly. Will have a look. In my experience, on the fly transformations (especially from global WGS84 to polar) lead to issues with broken vertices. This is why I've got an additional step in `mapr` to split the global polygon shapefile in two.

**Comment by jamesgrecian** [comment]
If you're happy with the current change to `mapr` I'll close the issue.

**Comment by ianjonsen** [comment]
makes sense to avoid those broken vertices issues... yep, happy to se it closed
